<a href="https://colab.research.google.com/github/JamesSoriano/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Final Exam

###Problem 1

In [35]:
import numpy as np
A = np.array([[1,1,1],[1,0,4],[0,0,5]]) #creation of Matrix
B = np.array([[89],[89],[95]]) #creation of Matrix
eql = np.linalg.inv(A).dot(B) #compute using dot product
print(eql) #to print or display

[[13.]
 [57.]
 [19.]]


###Problem 2

In [38]:
import numpy as np

A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]]) #creation of Matrix
print(A,"\n") #to print or display

inv_A = np.linalg.pinv(A) #inverse the given matrix
###If I use np.linalg.inv the code would get an error message that it is a singular matrix
###That is why I use pinv to get the approximate initial matrix so the code will run

print(inv_A,"\n") #to print or display
B = np.array([[5],[15],[-20]]) #creation of Matrix
print(B,"\n") #to print or display
X = np.dot(inv_A,B) #use the dot product method
print(X) #to print or display

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]] 

[[ 0.01048951  0.03146853 -0.04195804]
 [-0.0034965  -0.01048951  0.01398601]
 [ 0.0034965   0.01048951 -0.01398601]] 

[[  5]
 [ 15]
 [-20]] 

[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


###Problem 3

In [11]:
import numpy as np 
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]]) #creation of Matrix
print(A,"\n") #to print or display
w,v = np.linalg.eig(A) #Compute eigenvalues and right eigenvectors of a square array

print("The eigenvalues are: \n",w) #to print or display
print("The eigenvectors are: \n",v.round()) #to print or display

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalues are: 
 [-1.  3.  2.]
The eigenvectors are: 
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
