<a href="https://colab.research.google.com/github/JamesSoriano/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Midterm Exam

###Question 1

In [6]:
import numpy as np
#Create the square matrix whose length is 5
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(C)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


###Question 2

In [34]:
#To make the elements below principal diagonal zero
B = np.triu([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(B)

[[ 1  2  3  4  5]
 [ 0  7  8  9 10]
 [ 0  0 13 14 15]
 [ 0  0  0 19 20]
 [ 0  0  0  0 25]]


###Question 3

In [40]:
#Create a symmetrical matrix
G = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]])
print(G)

[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


###Question 4

In [16]:
#Matrix 3x3
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])

#To inverse the matrix
invC = np.linalg.inv(C)

print("The inverse matrix: \n")
print(invC)

The inverse matrix: 

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


###Question 5

In [18]:
#Matrix 3x3
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])

#To get the determinant of the matrix
detC = np.linalg.det(C)

print("The determinant: \n")
print(int(detC))

The determinant: 

5


###Question 6

In [22]:
#The constant variables in matrix
E = np.array([[5,4,1],
              [10,9,4],
              [10,13,15]])

#The equal variables in matrix
C = np.array([[[3.4],
               [8.8],
               [19.2]]])

#To determine the roots of the linear equations
roots = np.linalg.inv(E) @ C

print("The roots of linear equation: \n")
print(roots)

The roots of linear equation: 

[[[0.2]
  [0.4]
  [0.8]]]
