<a href="https://colab.research.google.com/github/JamesSoriano/Linear-Algerba-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical Lab Exam 1

##Problem 1

In [ ]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,],[3,4,],[5,6,]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2,],[3,4,]])
print("A=\n",A)
print()
print("B=\n",B)
print()
print("C=\n",C)
print()
print("D=\n",D)
print()
dot = np.dot(A,B)
print("a.\n",dot)
print()
print("b.\n",D+D)
print()
multiply = 2*(C)
print("c.\n",multiply)


A=
 [[1 2 3]
 [4 5 6]]

B=
 [[1 2]
 [3 4]
 [5 6]]

C=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

D=
 [[1 2]
 [3 4]]

a.
 [[22 28]
 [49 64]]

b.
 [[2 4]
 [6 8]]

c.
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


##Problem 2

In [2]:
import numpy as np
A = np.array([5, 3, -1])

print('Size of array:', A.size)
print('Type of array:', type(A))
print('Shape of array:', A.shape)
print('Dimension of array:', A.ndim)



Size of array: 3
Type of array: <class 'numpy.ndarray'>
Shape of array: (3,)
Dimension of array: 1
