<a href="https://colab.research.google.com/github/JamesSoriano/Linear-Algerba-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim Exam

###Question 1

In [22]:
import numpy as np

C = np.array(
         [[ 1,  0,  0,  0],
          [ 0,  1,  0,  0],
          [ 0,  0,  1,  0],
          [ 0,  0,  0,  1]]
            )

print(C)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


###Question 2

In [21]:
C = np.array(
         [[ 1,  0,  0,  0],
          [ 0,  1,  0,  0],
          [ 0,  0,  1,  0],
          [ 0,  0,  0,  1]]
            )

print(C*2)

[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]


###Question 3

In [20]:
A = [2,7,4] 
B = [3,9,8]

cross = np.cross(A,B)
print(cross)

[20 -4 -3]
