<a href="https://colab.research.google.com/github/JamesSoriano/Linear-Algerba-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vector Space Operations

##Representing Vectors

In [ ]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


##Describing Vectors in NumPy

In [ ]:
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

pool = np.array([ball1, ball2])
pool.shape
pool.ndim

2

In [ ]:
U = np.array([[1,2,3],[4,5,6]])
U
U.size

6

##Space

###Addition of Vectors

In [ ]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])

sum = addend1 + addend2
sum

array([1, 1, 0])

In [ ]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1,addend2)
resultant

array([1, 1, 0])

###Subtraction of Vector

In [ ]:
difference = addend1 - addend2
difference

array([-1, -1,  0])

In [ ]:
difference2 = np.subtract(addend1,addend2)
difference2

array([-1, -1,  0])

###Multiplication of Vector

In [ ]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

###Cross Product

In [ ]:
A = np.array([2,3,4])
B = np.array([1,7,1])
cross = np.cross(A,B)
print(cross)

[-25   2  11]


In [ ]:
import numpy as np
A = np.array([2,3])
B = np.array([1,7])

dot = np.dot(A,B)
print(dot)

23
