<a href="https://colab.research.google.com/github/Jaja0001/Linear-Algerba-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [28]:
#numpy
import numpy as np
print("A=")
A = np.array([[-5,0],[4,1]])
print(A)
print()
print("B=")
B = np.array([[6,-3],[2,3]])
print(B)
print()
print("A+B=")
print(A+B)
print()
print("B-A=")
print(B-A)
print()
print("A-B=")
print(A-B)

A=
[[-5  0]
 [ 4  1]]

B=
[[ 6 -3]
 [ 2  3]]

A+B=
[[ 1 -3]
 [ 6  4]]

B-A=
[[11 -3]
 [-2  2]]

A-B=
[[-11   3]
 [  2  -2]]
