<a href="https://colab.research.google.com/github/Jaja0001/Linear-Algerba-58019/blob/main/Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Algebra

In [1]:
#numpy
import numpy as np
a = np.array([1,2,3]) #This is an examplae of 1x3 matrix
print(a)

[1 2 3]


In [5]:
#numpy
import numpy as np
b = np.array([[1,2,3],[4,5,6]]) #This is an examplae of 2x3 matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
#numpy
import numpy as np
c = np.array([[1,2,3],[4,5,6],[7,8,9]]) #This is an examplae of 3x3 matrix
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
#numpy
import numpy as np
d = np.full((3,3),7)
print(d+d)
print(d-d)

[[14 14 14]
 [14 14 14]
 [14 14 14]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
#numpy
import numpy as np
e = np.array([[1,2,3],[4,5,6],[7,8,9]]) #This is an examplae of 3x3 matrix
print(e)
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [11]:
#numpy
import numpy as np
f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#numpy
import numpy as np
g = np.zeros((3,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
#numpy
import numpy as np
h = np.empty((0,12))
print(h)

[]
